# Generated by Django 4.1.6 on 2023-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeLink', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='availability',
            new_name='friday_availability',
        ),
        migrations.AddField(
            model_name='tutor',
            name='monday_availability',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='saturday_availability',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='sunday_availability',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='thursday_availability',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tuesday_availability',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='wednesday_availability',
            field=models.BigIntegerField(default=0),
        ),
    ]
