# Generated by Django 4.1.6 on 2023-03-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeLink', '0006_tutor_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('course', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeLink.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeLink.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeLink.tutor')),
            ],
        ),
    ]
