# Generated by Django 4.1.6 on 2023-03-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeLink', '0009_appointment_is_active_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeLink.course'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
