# Generated by Django 4.1.6 on 2023-05-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeLink', '0011_tutor_downvotes_tutor_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='students_rated',
            field=models.ManyToManyField(blank=True, to='KnowledgeLink.student'),
        ),
    ]
